remote_theme: daviddarnes/alembic


navigation_header:
  Home: /
  Project 1: /Project1/Lageman_Project1.html
  Project 2: /Project2/Project2_Lageman.html
  Project 3: /Project3/Project3_Lageman.html
  Project 4: /Project4/FinalProject_Lageman.html
  Project 5: /Project5/MS_Paper_1.html
  Project 6: /Project6/MS_Paper_2.html
  
navigation_footer:

