remote_theme: daviddarnes/alembic


navigation_header:
  Home: /
  Project 1: /Project1/Project1_Lageman.html
  Project 2: /Project2/Project2_Lageman.html
  Project 3: /Project3/GROW_Lageman.html
  Project 4: /Project4/FinalProject_Lageman.html
