# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

# Site settings
url: mydomain.com
baseurl: ''
title: 'My website'
description: 'This is my new website'
permalink: pretty
logo: "https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwjhtI-5tq7dAhWOdN8KHZ2yAqEQjRx6BAgBEAU&url=http%3A%2F%2Frickandmorty.wikia.com%2Fwiki%2FNoob-Noob&psig=AOvVaw3kGUdbzsv2kyGWMvwqAaaW&ust=1536599781420605"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/

# Footer nav
navigation_footer:
  Back to top: "#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    description: "My thoughts and ideas"
    feature_text: |
      Welcome to my blog!
      
    feature_image: "https://picsum.photos/2560/600?image=866"
